# Predicting Probability Wins Using NBA Data

## Project Scope

### CONTEXT

 - The sports industry is a fiercely competitive industry and NBA is no exception.
 - A consecutive poor performance may sink a franchise--- therefore, the goal is to win and bag the “Championship” title.
 - Attracting the most talented player and being able to offer them lucrative contracts is also based on their performance.
 - It is in the CONTEXT of “winning is everything” that this capstone project is all about.
 
### NEEDS

 - There are a lot of tools available that can predict chances of winning in sports like the NBA.
 - The need is to have a tool that is able to help coaches adjust their game plan and/or strategy based on what is currently happening (e.g., the opponent’s team current line up of players, who got the first ball, somebody from the team/opponent’s team got injured/fouled out, etc.)
 
### VISION

 - The team’s coach will initially get an initial prediction of their chances of winning based on historical data (i.e. data based on past games played against the specific opponent team they are playing against with).
 - Coach will be able to feed information (different game plays/strategies based on some assumptions) and pick the game play that will allow them to have more chances of winning.
 - During the actual game, the coach is also able to feed information (actual information especially on opponent’s side) and be able to adjust his game plan/strategy based on the prediction that will have the best outcome.

### OUTCOME

 - The main user (which is assumed to be the coach) will work closely with the data analyst/scientist. The application should be able to keep track of the data being fed on the tool. It should be able to keep track of the outcome (expected).
 - The actual game plan/strategy chosen by the coach will also be tracked and the actual outcome as well. Improvements to the tool should be based on the actual vs. expected outcomes.

## Data Dictionary

| Variable             | Values                  | Description                                       | Mnemonic               |
|----------------------|-------------------------|---------------------------------------------------|------------------------|
| Game ID              | String                  | Official Game ID at NBA.com                       | game_id                |
| Season Type          | String                  | Season that the dataset belongs to                | data_set               |
| Game Date            | MM/DD/YYYY              | Game date                                         | date                   |
| A1 | String | First player of away team who is one of the active players in the court | a1 |
| A2 | String | Second player of away team who is one of the active players in the court | a2 |
| A3 | String | Third player of away team who is one of the active players in the court | a3 |
| A4 | String | Fourth player of away team who is one of the active players in the court | a4 |
| A5 | String | Fifth player of away team who is one of the active players in the court | a5 |
| H1 | String | First player of home team who is one of the active players in the court | h1 |
| H2 | String | Second player of home team who is one of the active players in the court | h2 |
| H3 | String | Third player of home team who is one of the active players in the court | h3 |
| H4 | String | Fourth player of home team who is one of the active players in the court | h4 |
| H5 | String | Fifth player of home team who is one of the active players in the court | h5 |
| Period | Nominal Integer | Period of the game that the event described in actually occurred | period |
| Away Score | Integer | Accumulated score of away team at that moment in the game | away_score |
| Home Score | Integer | Accumulated score of home team at that moment in the game | home_score |
| Time Remaining | HH:MM:SS | Remaining time in the period | remaining_time |
| Time Elapsed | HH:MM:SS | Time passed since the period has started | elapsed |
| Length of Time | HH:MM:SS | Duration of the event described in that row | play_length |
| Play ID | Integer | ID number of the events in the game | play_id |
| Team | Nominal | Team that has executed the described event | team |
| Event Type | Nominal | Various types of events (fouls, shots, rebounds, freethrows, turnovers, etc.) | event_type |
| Assist | String | The player who made the assist if the event is a "shot" | assist |
| Jumpball Away | String | Player of away team who is participating in a jumpball | away |
| Jumpball Home | String | Player of home team who is participating in a jumpball | home |
| Block | String | Player who blocked a shot | block |
| Check In | String | Player who checks in the game | entered |
| Check Out | String | Player who checks out of the game | left |
| Freethrows | Ordinal Integer | Freethrows in an order (first, second, third, ...) | num |
| Opponent | String | Player who has drawn a foul | opponent |
| Number Freethrows | Integer | How many freethrows are going to be shoot | outof |
| Player Name | String | Player who executed the event | player |
| Points | Integer | Points scored within the event | points |
| Possession | String | Player who grabbed the ball after an event | possession |
| Reason | String | More details on how the event resulted | reason |
| Result | Nominal | Shot made or missed | result |
| Steal | String | Player who steals the ball | steal |
| Type | String | More details of the event | type |
| Distance | Integer | Shot distance in feet | shot_distance |
| NBA X | Integer | X axis value of that shot at NBA.com. X coordinates differs from -250 to +250 | original_x |
| NBA Y | Integer | Y axis value of that shot at NBA.com. Y coordinates differs from -51 to +870 | original_y |
| X | Integer | X in terms of FEET to reflect the court size which is 50 feet wide. differs from  0 to +50 | converted_x |
| Y | Integer | Y in terms of FEET to reflect the court size which is 94 feet long. differs from  0 to +94 | converted_y |
| Explanation | String | Text explanation of event | explanation |

## Environmental Scan

### Article 1: The problem with win probability

http://www.sloansportsconference.com/wp-content/uploads/2018/02/2011.pdf

 - Lacks sufficient context
   - Win probability models should be responsive to in-game contextual features such as injuries and fouls
 - No measure of uncertainty
   - There are many paths to any one outcome
 - No publicly available datasets or models for comparison
 
### Article 2: Statistical methods in sports with a focus on win probability and performance evaluation

https://lib.dr.iastate.edu/cgi/viewcontent.cgi?article=6969&context=etd

 - Discussed common methods of estimating in-game probability
 - Performance and usefulness of method in NHL, NBA, and NFL
 
### Insights from articles:

 - The use of play by play data in creating a model
 - The use of random forest as machine learning algorithm

## Key Challenges

1. Big Dataset 
 - The dataset will use 15 seasons of NBA. If researcher analyzes play-by-play data, this means dealing with millions of records. 
 - Researcher is not sure about how this will impact running codes in her local machine. A recommendation made was to put data in the cloud and work from there.

2. Las Vegas Spread
 - The articles found during environmental scan both used the Las Vegas Spread as one of its feature variables. Current dataset does not provide this. 
 - Researcher can use ELO ratings in place of this.
 
3. Random Forest
 - Researcher has no experience or does not have basic knowledge of Random Forest as a machine learning algorithm yet. This will be taught in her Data Science course but at a later time which may not be enough to complete the Capstone project.
 - If dataset and using Random Forest will really be challenging, researcher can re-scope the project to look into the data in a larger scale (instead of play-by-play, maybe just the final results and use this data instead). Researcher can also resort to using simpler machine learning algorithms like Linear Regression and/or Logistic Regression.
 
4. Data Transformation
 - Even though data is already clean, based on the data dictionary above, most variables are string or characters. Transforming data in categorical variables will be very challenging especially that it is a big dataset.
 - Researchers insufficient knowledge of the different NBA sports team names and team member names can be very challenging too when she does the transformation. Transforming some of the variables may not be that intuitive.

In [1]:
from tensorflow.python.lib.io import file_io
from pandas.compat import StringIO
import numpy as np
import pandas as pd

# read the input data
def read_data(gcs_path):
    print('downloading csv file from', gcs_path)     
    file_stream = file_io.FileIO(gcs_path, mode='r')
    data = pd.read_csv(StringIO(file_stream.read()))
    return data

/home/bocalbos/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/bocalbos/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/bocalbos/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/bocalbos/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/bocalbos/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/bocalbos/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/bocalbos/anaconda3/lib/python3.5/site-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
/home/bocalbos/anaconda3/lib/python3.5/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/bocalbos/anaconda3/lib/python3.5/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/bocalbos/anaconda3/lib/python3.5/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/bocalbos/anaconda3/lib/python3.5/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/bocalbos/anaconda3/lib/python3.5/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/bocalbos/anaconda3/lib/python3.5/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

### Combine all seasons in one dataframe

In [2]:
import os
mypath = 'gs://mynba/Play_By_Play/'
files = file_io.get_matching_files(os.path.join(mypath, '*.csv'))
df = pd.DataFrame()
fullnba_df = pd.DataFrame()
for file in files[0:11]:
    df = read_data(file)
    fullnba_df = pd.concat([df,fullnba_df])
fullnba_df.info()

downloading csv file from gs://mynba/Play_By_Play/2006_2007_season.csv
downloading csv file from gs://mynba/Play_By_Play/2007_2008_season.csv
downloading csv file from gs://mynba/Play_By_Play/2008_2009_season.csv

/home/bocalbos/anaconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2825: DtypeWarning: Columns (39,40,41,42) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):

downloading csv file from gs://mynba/Play_By_Play/2009_2010_season.csv
downloading csv file from gs://mynba/Play_By_Play/2010_2011_season.csv
downloading csv file from gs://mynba/Play_By_Play/2011_2012_season.csv
downloading csv file from gs://mynba/Play_By_Play/2012_2013_season.csv
downloading csv file from gs://mynba/Play_By_Play/2013_2014_season.csv
downloading csv file from gs://mynba/Play_By_Play/2014_2015_season.csv
downloading csv file from gs://mynba/Play_By_Play/2015_2016_season.csv
downloading csv file from gs://mynba/Play_By_Play/2016_2017_season.csv

/home/bocalbos/anaconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2825: DtypeWarning: Columns (38) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6402683 entries, 0 to 589610
Data columns (total 44 columns):
game_id           object
data_set          object
date              object
a1                object
a2                object
a3                object
a4                object
a5                object
h1                object
h2                object
h3                object
h4                object
h5                object
period            int64
away_score        int64
home_score        int64
remaining_time    object
elapsed           object
play_length       object
play_id           int64
team              object
event_type        object
assist            object
away              object
home              object
block             object
entered           object
left              object
num               float64
opponent          object
outof             float64
player            object
points            float64
possession        object
reason            object
result            object
steal             object
type              object
shot_distance     object
original_x        object
original_y        object
converted_x       object
converted_y       object
description       object
dtypes: float64(3), int64(4), object(37)
memory usage: 2.1+ GB

In [3]:
fullnba_df['game_id'] = fullnba_df['game_id'].astype(str).str.slice(start=4, stop=-1).astype(int)
fullnba_df.head()

,game_id,data_set,date,a1,a2,a3,a4,a5,h1,h2,...,reason,result,steal,type,shot_distance,original_x,original_y,converted_x,converted_y,description
0,21600001,2016-2017 Regular Season,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,...,NaN,NaN,NaN,start of period,NaN,NaN,NaN,NaN,NaN,NaN
1,21600001,2016-2017 Regular Season,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,...,NaN,NaN,NaN,jump ball,NaN,NaN,NaN,NaN,NaN,Jump Ball Thompson vs. Noah: Tip to Rose
2,21600001,2016-2017 Regular Season,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,...,NaN,made,NaN,Driving Layup,1,4,8,24.6,5.8,Rose 1' Driving Layup (2 PTS) (Noah 1 AST)
3,21600001,2016-2017 Regular Season,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,...,NaN,missed,NaN,Hook Shot,4,-11,36,23.9,85.4,MISS Love 4' Hook Shot
4,21600001,2016-2017 Regular Season,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,...,NaN,NaN,NaN,rebound defensive,NaN,NaN,NaN,NaN,NaN,Noah REBOUND (Off:0 Def:1)

In [4]:
mypath = 'gs://mynba/Play_By_Play/2017_2018_season.csv'
season18_df = read_data(mypath)
season18_df.info()

downloading csv file from gs://mynba/Play_By_Play/2017_2018_season.csv

/home/bocalbos/anaconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2825: DtypeWarning: Columns (38,39,40,41,42) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 599389 entries, 0 to 599388
Data columns (total 44 columns):
game_id           599389 non-null int64
data_set          599389 non-null object
date              599389 non-null object
a1                599389 non-null object
a2                599389 non-null object
a3                599389 non-null object
a4                599389 non-null object
a5                599389 non-null object
h1                599389 non-null object
h2                599389 non-null object
h3                599389 non-null object
h4                599389 non-null object
h5                599389 non-null object
period            599389 non-null int64
away_score        599389 non-null int64
home_score        599389 non-null int64
remaining_time    599389 non-null object
elapsed           599389 non-null object
play_length       599389 non-null object
play_id           599389 non-null int64
team              549049 non-null object
event_type        599389 non-null object
assist            60744 non-null object
away              2225 non-null object
home              2225 non-null object
block             12643 non-null object
entered           59163 non-null object
left              59163 non-null object
num               57019 non-null float64
opponent          52303 non-null object
outof             57019 non-null float64
player            549787 non-null object
points            282510 non-null float64
possession        2143 non-null object
reason            86746 non-null object
result            282510 non-null object
steal             20188 non-null object
type              599388 non-null object
shot_distance     225486 non-null object
original_x        225451 non-null object
original_y        225451 non-null object
converted_x       225451 non-null object
converted_y       225451 non-null object
description       585641 non-null object
dtypes: float64(3), int64(5), object(36)
memory usage: 201.2+ MB

In [5]:
finalnba_df = pd.concat([fullnba_df,season18_df])
finalnba_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7002072 entries, 0 to 599388
Data columns (total 44 columns):
game_id           int64
data_set          object
date              object
a1                object
a2                object
a3                object
a4                object
a5                object
h1                object
h2                object
h3                object
h4                object
h5                object
period            int64
away_score        int64
home_score        int64
remaining_time    object
elapsed           object
play_length       object
play_id           int64
team              object
event_type        object
assist            object
away              object
home              object
block             object
entered           object
left              object
num               float64
opponent          object
outof             float64
player            object
points            float64
possession        object
reason            object
result            object
steal             object
type              object
shot_distance     object
original_x        object
original_y        object
converted_x       object
converted_y       object
description       object
dtypes: float64(3), int64(5), object(36)
memory usage: 2.3+ GB

In [6]:
finalnba_df = finalnba_df.reset_index()
finalnba_df.drop('index',axis=1,inplace=True)
finalnba_df.head()

,game_id,data_set,date,a1,a2,a3,a4,a5,h1,h2,...,reason,result,steal,type,shot_distance,original_x,original_y,converted_x,converted_y,description
0,21600001,2016-2017 Regular Season,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,...,NaN,NaN,NaN,start of period,NaN,NaN,NaN,NaN,NaN,NaN
1,21600001,2016-2017 Regular Season,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,...,NaN,NaN,NaN,jump ball,NaN,NaN,NaN,NaN,NaN,Jump Ball Thompson vs. Noah: Tip to Rose
2,21600001,2016-2017 Regular Season,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,...,NaN,made,NaN,Driving Layup,1,4,8,24.6,5.8,Rose 1' Driving Layup (2 PTS) (Noah 1 AST)
3,21600001,2016-2017 Regular Season,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,...,NaN,missed,NaN,Hook Shot,4,-11,36,23.9,85.4,MISS Love 4' Hook Shot
4,21600001,2016-2017 Regular Season,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,...,NaN,NaN,NaN,rebound defensive,NaN,NaN,NaN,NaN,NaN,Noah REBOUND (Off:0 Def:1)

In [7]:
def nas_sorted(df):
    return df.isnull().sum().sort_values(ascending = False)

In [8]:
sorted_nas = nas_sorted(finalnba_df)
sorted_nas

possession        6976944
home              6975526
away              6975526
block             6849671
steal             6769321
left              6362846
entered           6362846
opponent          6362591
assist            6327923
num               6266130
outof             6266130
reason            5912350
converted_x       4447860
converted_y       4447860
original_y        4447860
original_x        4447860
shot_distance     4447825
points            3711878
result            3711878
team               633613
player             625498
description        176177
type                    1
h3                      0
data_set                0
date                    0
a1                      0
a2                      0
a3                      0
a4                      0
a5                      0
h1                      0
h2                      0
event_type              0
h4                      0
h5                      0
period                  0
away_score              0
home_score              0
remaining_time          0
elapsed                 0
play_length             0
play_id                 0
game_id                 0
dtype: int64

In [9]:
finalnba_df['game_id'].unique()

array([21600001, 21600002, 21600003, ..., 41700402, 41700403, 41700404])

### Merged NBA Schedule to get Home and Away team names

In [10]:
mypath = 'gs://mynba/Schedule'
files = file_io.get_matching_files(os.path.join(mypath, '*.csv'))
df = pd.DataFrame()
schedule_df = pd.DataFrame()
for file in files:
    df = read_data(file)
    schedule_df = pd.concat([df,schedule_df])
schedule_df.info()

downloading csv file from gs://mynba/Schedule/2006-2007_NBA_Historical_Schedule.csv
downloading csv file from gs://mynba/Schedule/2007-2008_NBA_Historical_Schedule.csv
downloading csv file from gs://mynba/Schedule/2008-2009_NBA_Historical_Schedule.csv
downloading csv file from gs://mynba/Schedule/2009-2010_NBA_Historical_Schedule.csv
downloading csv file from gs://mynba/Schedule/2010-2011_NBA_Historical_Schedule.csv
downloading csv file from gs://mynba/Schedule/2011-2012_NBA_Historical_Schedule.csv
downloading csv file from gs://mynba/Schedule/2012-2013_NBA_Historical_Schedule.csv
downloading csv file from gs://mynba/Schedule/2013-2014_NBA_Historical_Schedule.csv
downloading csv file from gs://mynba/Schedule/2014-2015_NBA_Historical_Schedule.csv
downloading csv file from gs://mynba/Schedule/2015-2016_NBA_Historical_Schedule.csv
downloading csv file from gs://mynba/Schedule/2016-2017_NBA_Historical_Schedule.csv
downloading csv file from gs://mynba/Schedule/2017-2018_NBA_Historical_Schedule.csv
<class 'pandas.core.frame.DataFrame'>
Int64Index: 15518 entries, 0 to 1308
Data columns (total 12 columns):
DATASET                  15518 non-null object
GAME ID                  15518 non-null int64
DATE                     15518 non-null object
TIME                     15518 non-null object
ROAD TEAM                15518 non-null object
HOME TEAM                15518 non-null object
TOTAL GAME MINUTES       15518 non-null float64
ROAD TEAM FINAL SCORE    15518 non-null int64
HOME TEAM FINAL SCORE    15518 non-null int64
ROAD TEAM REST           15518 non-null object
HOME TEAM REST           15518 non-null object
BOX SCORE URL            15518 non-null object
dtypes: float64(1), int64(3), object(8)
memory usage: 1.5+ MB

In [11]:
schedule_df[['GAME ID', 'ROAD TEAM', 'HOME TEAM']]
schedule_df.head()

,DATASET,GAME ID,DATE,TIME,ROAD TEAM,HOME TEAM,TOTAL GAME MINUTES,ROAD TEAM FINAL SCORE,HOME TEAM FINAL SCORE,ROAD TEAM REST,HOME TEAM REST,BOX SCORE URL
0,2017-2018 Regular Season,21700001,10/17/2017,8:00 PM,Boston,Cleveland,240.0,99,102,3+,3+,Box Score
1,2017-2018 Regular Season,21700002,10/17/2017,10:30 PM,Houston,Golden State,240.0,122,121,3+,3+,Box Score
2,2017-2018 Regular Season,21700003,10/18/2017,7:00 PM,Charlotte,Detroit,240.0,90,102,3+,3+,Box Score
3,2017-2018 Regular Season,21700004,10/18/2017,7:00 PM,Brooklyn,Indiana,240.0,131,140,3+,3+,Box Score
4,2017-2018 Regular Season,21700005,10/18/2017,7:00 PM,Miami,Orlando,240.0,109,116,3+,3+,Box Score

In [12]:
schedule_df.rename(columns={"GAME ID": "game_id", "ROAD TEAM": "away_team", "HOME TEAM": "home_team"}, inplace=True)

In [13]:
copied_fullnba = finalnba_df.copy()
copied_fullnba.head()

,game_id,data_set,date,a1,a2,a3,a4,a5,h1,h2,...,reason,result,steal,type,shot_distance,original_x,original_y,converted_x,converted_y,description
0,21600001,2016-2017 Regular Season,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,...,NaN,NaN,NaN,start of period,NaN,NaN,NaN,NaN,NaN,NaN
1,21600001,2016-2017 Regular Season,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,...,NaN,NaN,NaN,jump ball,NaN,NaN,NaN,NaN,NaN,Jump Ball Thompson vs. Noah: Tip to Rose
2,21600001,2016-2017 Regular Season,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,...,NaN,made,NaN,Driving Layup,1,4,8,24.6,5.8,Rose 1' Driving Layup (2 PTS) (Noah 1 AST)
3,21600001,2016-2017 Regular Season,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,...,NaN,missed,NaN,Hook Shot,4,-11,36,23.9,85.4,MISS Love 4' Hook Shot
4,21600001,2016-2017 Regular Season,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,...,NaN,NaN,NaN,rebound defensive,NaN,NaN,NaN,NaN,NaN,Noah REBOUND (Off:0 Def:1)

In [14]:
finalnba_df = pd.merge(finalnba_df, schedule_df[['game_id', 'away_team', 'home_team']], on='game_id')
finalnba_df.head()

,game_id,data_set,date,a1,a2,a3,a4,a5,h1,h2,...,steal,type,shot_distance,original_x,original_y,converted_x,converted_y,description,away_team,home_team
0,21600001,2016-2017 Regular Season,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,...,NaN,start of period,NaN,NaN,NaN,NaN,NaN,NaN,New York,Cleveland
1,21600001,2016-2017 Regular Season,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,...,NaN,jump ball,NaN,NaN,NaN,NaN,NaN,Jump Ball Thompson vs. Noah: Tip to Rose,New York,Cleveland
2,21600001,2016-2017 Regular Season,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,...,NaN,Driving Layup,1,4,8,24.6,5.8,Rose 1' Driving Layup (2 PTS) (Noah 1 AST),New York,Cleveland
3,21600001,2016-2017 Regular Season,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,...,NaN,Hook Shot,4,-11,36,23.9,85.4,MISS Love 4' Hook Shot,New York,Cleveland
4,21600001,2016-2017 Regular Season,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,...,NaN,rebound defensive,NaN,NaN,NaN,NaN,NaN,Noah REBOUND (Off:0 Def:1),New York,Cleveland

In [15]:
finalnba_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7002072 entries, 0 to 7002071
Data columns (total 46 columns):
game_id           int64
data_set          object
date              object
a1                object
a2                object
a3                object
a4                object
a5                object
h1                object
h2                object
h3                object
h4                object
h5                object
period            int64
away_score        int64
home_score        int64
remaining_time    object
elapsed           object
play_length       object
play_id           int64
team              object
event_type        object
assist            object
away              object
home              object
block             object
entered           object
left              object
num               float64
opponent          object
outof             float64
player            object
points            float64
possession        object
reason            object
result            object
steal             object
type              object
shot_distance     object
original_x        object
original_y        object
converted_x       object
converted_y       object
description       object
away_team         object
home_team         object
dtypes: float64(3), int64(5), object(38)
memory usage: 2.5+ GB

### Calculating Target Variable Home Win/Lose Result

In [16]:
index = finalnba_df[finalnba_df['play_id'] == 0].index.values - 1
index = np.delete(index, 0)
index = np.append(index, finalnba_df.shape[0] - 1)
index

array([    485,     903,    1380, ..., 6401805, 6402222, 7002071])

In [17]:
winlose_df = finalnba_df[['game_id', 'period', 'away_score', 'home_score', 'remaining_time']].iloc[index]
winlose_df = winlose_df.reset_index()

In [18]:
winlose_df.drop('index',axis=1,inplace=True)
winlose_df

        game_id  period  away_score  home_score remaining_time
0      21600001       4          88         117       00:00:00
1      21600002       4         104         113       00:00:00
2      21600003       4         129         100       00:00:00
3      21600004       4         108          96       00:00:00
4      21600005       5         121         130       00:00:00
5      21600006       4         117         122       00:00:00
6      21600007       4          91         109       00:00:00
7      21600008       4         107          96       00:00:00
8      21600009       4          98         102       00:00:00
9      21600010       4         107         102       00:00:00
10     21600011       4         103          97       00:00:00
11     21600012       4         113          94       00:00:00
12     21600013       4         114         120       00:00:00
13     21600014       4          99         114       00:00:00
14     21600015       4          99         105       00:00:00
15     21600016       4         102          94       00:00:00
16     21600017       4         114         106       00:00:00
17     21600018       4          94          91       00:00:00
18     21600019       4          94         103       00:00:00
19     21600020       4          82         108       00:00:00
20     21600021       5         110         113       00:00:00
21     21600022       4          97          91       00:00:00
22     21600023       4         106          98       00:00:00
23     21600024       4          89          96       00:00:00
24     21600025       4         122         114       00:00:00
25     21600026       4         104          72       00:00:00
26     21600027       4         104          98       00:00:00
27     21600028       4         104         111       00:00:00
28     21600029       4          99         105       00:00:00
29     21600030       4         101         118       00:00:00
...         ...     ...         ...         ...            ...
13483  40600222       5         117         127       00:00:00
13484  40600203       4          81          74       00:00:00
13485  40600223       4         105         125       00:00:00
13486  40600213       4          85          96       00:00:00
13487  40600233       4         101         108       00:00:00
13488  40600204       4          87         102       00:00:00
13489  40600224       4         115         101       00:00:00
13490  40600214       4          87          85       00:00:00
13491  40600234       4         104          98       00:00:00
13492  40600205       4         108          92       00:00:00
13493  40600225       4          87         100       00:00:00
13494  40600215       4          83          72       00:00:00
13495  40600235       4          88          85       00:00:00
13496  40600206       4          95          85       00:00:00
13497  40600216       4          88          72       00:00:00
13498  40600236       4         106         114       00:00:00
13499  40600311       4         100         108       00:00:00
13500  40600301       4          76          79       00:00:00
13501  40600302       4          76          79       00:00:00
13502  40600313       4          83         109       00:00:00
13503  40600303       4          82          88       00:00:00
13504  40600314       4          91          79       00:00:00
13505  40600304       4          87          91       00:00:00
13506  40600315       4          84         109       00:00:00
13507  40600305       6         109         107       00:00:00
13508  40600306       4          82          98       00:00:00
13509  40600401       4          76          85       00:00:00
13510  40600402       4          92         103       00:00:00
13511  40600403       4          75          72       00:00:00
13512  41700404       4         108          85        0:00:00

[13513 rows x 5 columns]

In [19]:
win_df = winlose_df[winlose_df['home_score']>winlose_df['away_score']]
win_df['W_or_L'] = 'win'
win_df.head()

/home/bocalbos/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

    game_id  period  away_score  home_score remaining_time W_or_L
0  21600001       4          88         117       00:00:00    win
1  21600002       4         104         113       00:00:00    win
4  21600005       5         121         130       00:00:00    win
5  21600006       4         117         122       00:00:00    win
6  21600007       4          91         109       00:00:00    win

In [20]:
lose_df = winlose_df[winlose_df['home_score']<winlose_df['away_score']]
lose_df['W_or_L'] = 'lose'
lose_df.head()

/home/bocalbos/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

     game_id  period  away_score  home_score remaining_time W_or_L
2   21600003       4         129         100       00:00:00   lose
3   21600004       4         108          96       00:00:00   lose
7   21600008       4         107          96       00:00:00   lose
9   21600010       4         107         102       00:00:00   lose
10  21600011       4         103          97       00:00:00   lose

In [21]:
winlose_df = pd.concat([win_df,lose_df])
winlose_df.head()

    game_id  period  away_score  home_score remaining_time W_or_L
0  21600001       4          88         117       00:00:00    win
1  21600002       4         104         113       00:00:00    win
4  21600005       5         121         130       00:00:00    win
5  21600006       4         117         122       00:00:00    win
6  21600007       4          91         109       00:00:00    win

In [22]:
newnba_df = pd.merge(finalnba_df, winlose_df[['game_id', 'W_or_L']], how='outer', on='game_id')
newnba_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7002072 entries, 0 to 7002071
Data columns (total 47 columns):
game_id           int64
data_set          object
date              object
a1                object
a2                object
a3                object
a4                object
a5                object
h1                object
h2                object
h3                object
h4                object
h5                object
period            int64
away_score        int64
home_score        int64
remaining_time    object
elapsed           object
play_length       object
play_id           int64
team              object
event_type        object
assist            object
away              object
home              object
block             object
entered           object
left              object
num               float64
opponent          object
outof             float64
player            object
points            float64
possession        object
reason            object
result            object
steal             object
type              object
shot_distance     object
original_x        object
original_y        object
converted_x       object
converted_y       object
description       object
away_team         object
home_team         object
W_or_L            object
dtypes: float64(3), int64(5), object(39)
memory usage: 2.5+ GB

In [23]:
newnba_df[:5].T

,0,1,2,3,4
game_id,21600001,21600001,21600001,21600001,21600001
data_set,2016-2017 Regular Season,2016-2017 Regular Season,2016-2017 Regular Season,2016-2017 Regular Season,2016-2017 Regular Season
date,2016-10-25,2016-10-25,2016-10-25,2016-10-25,2016-10-25
a1,Carmelo Anthony,Carmelo Anthony,Carmelo Anthony,Carmelo Anthony,Carmelo Anthony
a2,Kristaps Porzingis,Kristaps Porzingis,Kristaps Porzingis,Kristaps Porzingis,Kristaps Porzingis
a3,Joakim Noah,Joakim Noah,Joakim Noah,Joakim Noah,Joakim Noah
a4,Courtney Lee,Courtney Lee,Courtney Lee,Courtney Lee,Courtney Lee
a5,Derrick Rose,Derrick Rose,Derrick Rose,Derrick Rose,Derrick Rose
h1,LeBron James,LeBron James,LeBron James,LeBron James,LeBron James
h2,Kevin Love,Kevin Love,Kevin Love,Kevin Love,Kevin Love
h3,Tristan Thompson,Tristan Thompson,Tristan Thompson,Tristan Thompson,Tristan Thompson
h4,JR Smith,JR Smith,JR Smith,JR Smith,JR Smith
h5,Kyrie Irving,Kyrie Irving,Kyrie Irving,Kyrie Irving,Kyrie Irving
period,1,1,1,1,1
away_score,0,0,2,2,2
home_score,0,0,0,0,0
remaining_time,00:12:00,00:12:00,00:11:40,00:11:26,00:11:23
elapsed,00:00:00,00:00:00,00:00:20,00:00:34,00:00:37
play_length,00:00:00,00:00:00,00:00:20,00:00:14,00:00:03
play_id,0,1,2,3,4
team,NaN,NYK,NYK,CLE,NYK
event_type,start of period,jump ball,shot,miss,rebound
assist,NaN,NaN,Joakim Noah,NaN,NaN
away,NaN,Joakim Noah,NaN,NaN,NaN
home,NaN,Tristan Thompson,NaN,NaN,NaN
block,NaN,NaN,NaN,NaN,NaN
entered,NaN,NaN,NaN,NaN,NaN
left,NaN,NaN,NaN,NaN,NaN
num,NaN,NaN,NaN,NaN,NaN
opponent,NaN,NaN,NaN,NaN,NaN
outof,NaN,NaN,NaN,NaN,NaN
player,NaN,Tristan Thompson,Derrick Rose,Kevin Love,Joakim Noah
points,NaN,NaN,2,0,NaN
possession,NaN,Derrick Rose,NaN,NaN,NaN
reason,NaN,NaN,NaN,NaN,NaN
result,NaN,NaN,made,missed,NaN
steal,NaN,NaN,NaN,NaN,NaN
type,start of period,jump ball,Driving Layup,Hook Shot,rebound defensive
shot_distance,NaN,NaN,1,4,NaN
original_x,NaN,NaN,4,-11,NaN
original_y,NaN,NaN,8,36,NaN
converted_x,NaN,NaN,24.6,23.9,NaN
converted_y,NaN,NaN,5.8,85.4,NaN
description,NaN,Jump Ball Thompson vs. Noah: Tip to Rose,Rose 1' Driving Layup (2 PTS) (Noah 1 AST),MISS Love 4' Hook Shot,Noah REBOUND (Off:0 Def:1)
away_team,New York,New York,New York,New York,New York
home_team,Cleveland,Cleveland,Cleveland,Cleveland,Cleveland
W_or_L,win,win,win,win,win

In [24]:
newnba_df_na = nas_sorted(newnba_df)
newnba_df_na

possession        6976944
away              6975526
home              6975526
block             6849671
steal             6769321
left              6362846
entered           6362846
opponent          6362591
assist            6327923
outof             6266130
num               6266130
reason            5912350
converted_y       4447860
converted_x       4447860
original_y        4447860
original_x        4447860
shot_distance     4447825
result            3711878
points            3711878
W_or_L             902313
team               633613
player             625498
description        176177
type                    1
h4                      0
data_set                0
date                    0
a1                      0
a2                      0
a3                      0
a4                      0
a5                      0
h1                      0
h2                      0
h3                      0
period                  0
h5                      0
away_score              0
home_score              0
remaining_time          0
elapsed                 0
play_length             0
play_id                 0
event_type              0
away_team               0
home_team               0
game_id                 0
dtype: int64

In [25]:
newnba_df['team'].unique()

array([nan, 'NYK', 'CLE', 'UTA', 'POR', 'SAS', 'GSW', 'MIA', 'ORL', 'IND',
       'DAL', 'BKN', 'BOS', 'DET', 'TOR', 'MIL', 'CHA', 'MIN', 'MEM',
       'DEN', 'NOP', 'OKC', 'PHI', 'SAC', 'PHX', 'HOU', 'LAL', 'WAS',
       'ATL', 'CHI', 'LAC', 'NOH', 'NJN', 'SEA', 'NOK'], dtype=object)

In [26]:
newnba_df['home_team'].unique()

array(['Cleveland', 'Portland', 'Golden State', 'Orlando', 'Indiana',
       'Boston', 'Toronto', 'Milwaukee', 'Memphis', 'New Orleans',
       'Philadelphia', 'Phoenix', 'LA Lakers', 'Atlanta', 'Chicago',
       'Sacramento', 'Brooklyn', 'Detroit', 'Oklahoma City', 'Miami',
       'Dallas', 'Utah', 'Charlotte', 'New York', 'San Antonio', 'Denver',
       'LA Clippers', 'Houston', 'Minnesota', 'Washington', 'New Jersey',
       'Seattle', 'New Orleans/Oklahoma City'], dtype=object)

In [27]:
name_dic = {'Miami': 'MIA', 'LA Lakers': 'LAL', 'Philadelphia': 'PHI', 'Charlotte': 'CHA', 'Orlando': 'ORL',
       'Boston':'BOS', 'New Jersey': 'NJN', 'Detroit': 'DET', 'Cleveland': 'CLE', 'Memphis': 'MEM',
       'Minnesota': 'MIN', 'Utah': 'UTA', 'Seattle': 'SEA', 'Phoenix': 'PHX', 'Golden State': 'GSW',
       'Dallas': 'DAL', 'LA Clippers': 'LAC', 'Toronto': 'TOR', 'Indiana': 'IND', 'Atlanta': 'ATL',
       'San Antonio': 'SAS', 'Chicago': 'CHI', 'Denver': 'DEN', 'Washington': 'WAS', 'New York': 'NYK',
       'Milwaukee': 'MIL', 'Houston': 'HOU', 'Portland': 'POR', 'New Orleans/Oklahoma City': 'CHA',
       'Sacramento': 'SAC', 'Oklahoma City':'OKC', 'Brooklyn':'BKN', 'New Orleans':'NOP'}

In [28]:
newnba_df['home_team'].replace(to_replace = name_dic, inplace = True)

In [29]:
newnba_df['away_team'].replace(to_replace = name_dic, inplace = True)

In [30]:
newnba_df['home_team'].unique()

array(['CLE', 'POR', 'GSW', 'ORL', 'IND', 'BOS', 'TOR', 'MIL', 'MEM',
       'NOP', 'PHI', 'PHX', 'LAL', 'ATL', 'CHI', 'SAC', 'BKN', 'DET',
       'OKC', 'MIA', 'DAL', 'UTA', 'CHA', 'NYK', 'SAS', 'DEN', 'LAC',
       'HOU', 'MIN', 'WAS', 'NJN', 'SEA'], dtype=object)

In [31]:
newnba_df['team'].unique()

array([nan, 'NYK', 'CLE', 'UTA', 'POR', 'SAS', 'GSW', 'MIA', 'ORL', 'IND',
       'DAL', 'BKN', 'BOS', 'DET', 'TOR', 'MIL', 'CHA', 'MIN', 'MEM',
       'DEN', 'NOP', 'OKC', 'PHI', 'SAC', 'PHX', 'HOU', 'LAL', 'WAS',
       'ATL', 'CHI', 'LAC', 'NOH', 'NJN', 'SEA', 'NOK'], dtype=object)

In [32]:
newnba_df['team'].replace(to_replace = {'NOH':'NOP'}, inplace = True)

In [33]:
newnba_df['team'].replace(to_replace = {'NOK':'CHA'}, inplace = True)

In [34]:
newnba_df['team'].fillna(newnba_df['home_team'],inplace=True)
newnba_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7002072 entries, 0 to 7002071
Data columns (total 47 columns):
game_id           int64
data_set          object
date              object
a1                object
a2                object
a3                object
a4                object
a5                object
h1                object
h2                object
h3                object
h4                object
h5                object
period            int64
away_score        int64
home_score        int64
remaining_time    object
elapsed           object
play_length       object
play_id           int64
team              object
event_type        object
assist            object
away              object
home              object
block             object
entered           object
left              object
num               float64
opponent          object
outof             float64
player            object
points            float64
possession        object
reason            object
result            object
steal             object
type              object
shot_distance     object
original_x        object
original_y        object
converted_x       object
converted_y       object
description       object
away_team         object
home_team         object
W_or_L            object
dtypes: float64(3), int64(5), object(39)
memory usage: 2.5+ GB

In [35]:
newnba_df_na = nas_sorted(newnba_df)
newnba_df_na

possession        6976944
away              6975526
home              6975526
block             6849671
steal             6769321
left              6362846
entered           6362846
opponent          6362591
assist            6327923
outof             6266130
num               6266130
reason            5912350
converted_y       4447860
converted_x       4447860
original_y        4447860
original_x        4447860
shot_distance     4447825
result            3711878
points            3711878
W_or_L             902313
player             625498
description        176177
type                    1
h4                      0
data_set                0
date                    0
a1                      0
a2                      0
a3                      0
a4                      0
a5                      0
h1                      0
h2                      0
h3                      0
period                  0
h5                      0
away_score              0
home_score              0
remaining_time          0
elapsed                 0
play_length             0
play_id                 0
team                    0
event_type              0
away_team               0
home_team               0
game_id                 0
dtype: int64

### Block Statistics

In [36]:
home_blk = newnba_df.loc[(newnba_df['team'] == newnba_df['home_team']) & (newnba_df['event_type']=='rebound')]\
                                                .groupby('game_id').count()[['event_type']]\
                                                .rename(columns={'event_type':'num_block'})
home_blk = home_blk.reset_index()
home_blk.head()

    game_id  num_block
0  20600001         49
1  20600002         57
2  20600003         58
3  20600004         64
4  20600005         61

In [37]:
def merge_df(df1,df2,on,how='outer'):
    df = pd.merge(df1,df2,on=on,how=how)
    return df

In [38]:
def replace_col(df,column,newname):
    df = df.rename(columns={column:name}, inplace=True)
    return df

In [39]:
def drop_col(df,columns_to_drop):
    return df.drop([columns_to_drop],axis=1,inplace=True)

In [40]:
newnba_df = merge_df(newnba_df,home_blk,on='game_id')
newnba_df[:5].T

,0,1,2,3,4
game_id,21600001,21600001,21600001,21600001,21600001
data_set,2016-2017 Regular Season,2016-2017 Regular Season,2016-2017 Regular Season,2016-2017 Regular Season,2016-2017 Regular Season
date,2016-10-25,2016-10-25,2016-10-25,2016-10-25,2016-10-25
a1,Carmelo Anthony,Carmelo Anthony,Carmelo Anthony,Carmelo Anthony,Carmelo Anthony
a2,Kristaps Porzingis,Kristaps Porzingis,Kristaps Porzingis,Kristaps Porzingis,Kristaps Porzingis
a3,Joakim Noah,Joakim Noah,Joakim Noah,Joakim Noah,Joakim Noah
a4,Courtney Lee,Courtney Lee,Courtney Lee,Courtney Lee,Courtney Lee
a5,Derrick Rose,Derrick Rose,Derrick Rose,Derrick Rose,Derrick Rose
h1,LeBron James,LeBron James,LeBron James,LeBron James,LeBron James
h2,Kevin Love,Kevin Love,Kevin Love,Kevin Love,Kevin Love
h3,Tristan Thompson,Tristan Thompson,Tristan Thompson,Tristan Thompson,Tristan Thompson
h4,JR Smith,JR Smith,JR Smith,JR Smith,JR Smith
h5,Kyrie Irving,Kyrie Irving,Kyrie Irving,Kyrie Irving,Kyrie Irving
period,1,1,1,1,1
away_score,0,0,2,2,2
home_score,0,0,0,0,0
remaining_time,00:12:00,00:12:00,00:11:40,00:11:26,00:11:23
elapsed,00:00:00,00:00:00,00:00:20,00:00:34,00:00:37
play_length,00:00:00,00:00:00,00:00:20,00:00:14,00:00:03
play_id,0,1,2,3,4
team,CLE,NYK,NYK,CLE,NYK
event_type,start of period,jump ball,shot,miss,rebound
assist,NaN,NaN,Joakim Noah,NaN,NaN
away,NaN,Joakim Noah,NaN,NaN,NaN
home,NaN,Tristan Thompson,NaN,NaN,NaN
block,NaN,NaN,NaN,NaN,NaN
entered,NaN,NaN,NaN,NaN,NaN
left,NaN,NaN,NaN,NaN,NaN
num,NaN,NaN,NaN,NaN,NaN
opponent,NaN,NaN,NaN,NaN,NaN
outof,NaN,NaN,NaN,NaN,NaN
player,NaN,Tristan Thompson,Derrick Rose,Kevin Love,Joakim Noah
points,NaN,NaN,2,0,NaN
possession,NaN,Derrick Rose,NaN,NaN,NaN
reason,NaN,NaN,NaN,NaN,NaN
result,NaN,NaN,made,missed,NaN
steal,NaN,NaN,NaN,NaN,NaN
type,start of period,jump ball,Driving Layup,Hook Shot,rebound defensive
shot_distance,NaN,NaN,1,4,NaN
original_x,NaN,NaN,4,-11,NaN
original_y,NaN,NaN,8,36,NaN
converted_x,NaN,NaN,24.6,23.9,NaN
converted_y,NaN,NaN,5.8,85.4,NaN
description,NaN,Jump Ball Thompson vs. Noah: Tip to Rose,Rose 1' Driving Layup (2 PTS) (Noah 1 AST),MISS Love 4' Hook Shot,Noah REBOUND (Off:0 Def:1)
away_team,NYK,NYK,NYK,NYK,NYK
home_team,CLE,CLE,CLE,CLE,CLE
W_or_L,win,win,win,win,win
num_block,72,72,72,72,72

### Shots Made

In [41]:
home_shot = newnba_df.loc[(newnba_df['team']==newnba_df['home_team']) & (newnba_df['event_type']=='shot')]\
                                              .groupby('game_id').count()[['event_type']]\
                                              .rename(columns={'event_type':'shots_made'})
home_shot = home_shot.reset_index()
home_shot.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15489 entries, 0 to 15488
Data columns (total 2 columns):
game_id       15489 non-null int64
shots_made    15489 non-null int64
dtypes: int64(2)
memory usage: 242.1 KB

In [42]:
newnba_df = merge_df(newnba_df,home_shot,on='game_id')
newnba_df[:5].T

,0,1,2,3,4
game_id,21600001,21600001,21600001,21600001,21600001
data_set,2016-2017 Regular Season,2016-2017 Regular Season,2016-2017 Regular Season,2016-2017 Regular Season,2016-2017 Regular Season
date,2016-10-25,2016-10-25,2016-10-25,2016-10-25,2016-10-25
a1,Carmelo Anthony,Carmelo Anthony,Carmelo Anthony,Carmelo Anthony,Carmelo Anthony
a2,Kristaps Porzingis,Kristaps Porzingis,Kristaps Porzingis,Kristaps Porzingis,Kristaps Porzingis
a3,Joakim Noah,Joakim Noah,Joakim Noah,Joakim Noah,Joakim Noah
a4,Courtney Lee,Courtney Lee,Courtney Lee,Courtney Lee,Courtney Lee
a5,Derrick Rose,Derrick Rose,Derrick Rose,Derrick Rose,Derrick Rose
h1,LeBron James,LeBron James,LeBron James,LeBron James,LeBron James
h2,Kevin Love,Kevin Love,Kevin Love,Kevin Love,Kevin Love
h3,Tristan Thompson,Tristan Thompson,Tristan Thompson,Tristan Thompson,Tristan Thompson
h4,JR Smith,JR Smith,JR Smith,JR Smith,JR Smith
h5,Kyrie Irving,Kyrie Irving,Kyrie Irving,Kyrie Irving,Kyrie Irving
period,1,1,1,1,1
away_score,0,0,2,2,2
home_score,0,0,0,0,0
remaining_time,00:12:00,00:12:00,00:11:40,00:11:26,00:11:23
elapsed,00:00:00,00:00:00,00:00:20,00:00:34,00:00:37
play_length,00:00:00,00:00:00,00:00:20,00:00:14,00:00:03
play_id,0,1,2,3,4
team,CLE,NYK,NYK,CLE,NYK
event_type,start of period,jump ball,shot,miss,rebound
assist,NaN,NaN,Joakim Noah,NaN,NaN
away,NaN,Joakim Noah,NaN,NaN,NaN
home,NaN,Tristan Thompson,NaN,NaN,NaN
block,NaN,NaN,NaN,NaN,NaN
entered,NaN,NaN,NaN,NaN,NaN
left,NaN,NaN,NaN,NaN,NaN
num,NaN,NaN,NaN,NaN,NaN
opponent,NaN,NaN,NaN,NaN,NaN
outof,NaN,NaN,NaN,NaN,NaN
player,NaN,Tristan Thompson,Derrick Rose,Kevin Love,Joakim Noah
points,NaN,NaN,2,0,NaN
possession,NaN,Derrick Rose,NaN,NaN,NaN
reason,NaN,NaN,NaN,NaN,NaN
result,NaN,NaN,made,missed,NaN
steal,NaN,NaN,NaN,NaN,NaN
type,start of period,jump ball,Driving Layup,Hook Shot,rebound defensive
shot_distance,NaN,NaN,1,4,NaN
original_x,NaN,NaN,4,-11,NaN
original_y,NaN,NaN,8,36,NaN
converted_x,NaN,NaN,24.6,23.9,NaN
converted_y,NaN,NaN,5.8,85.4,NaN
description,NaN,Jump Ball Thompson vs. Noah: Tip to Rose,Rose 1' Driving Layup (2 PTS) (Noah 1 AST),MISS Love 4' Hook Shot,Noah REBOUND (Off:0 Def:1)
away_team,NYK,NYK,NYK,NYK,NYK
home_team,CLE,CLE,CLE,CLE,CLE
W_or_L,win,win,win,win,win
num_block,72,72,72,72,72
shots_made,45,45,45,45,45

### Missed Shots

In [43]:
home_miss = newnba_df.loc[(newnba_df['team'] == newnba_df['home_team']) & (newnba_df['event_type'] == 'miss')]\
                                               .groupby('game_id').count()[['event_type']]\
                                               .rename(columns={'event_type':'shots_missed'})
home_miss = home_miss.reset_index()
home_miss.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15489 entries, 0 to 15488
Data columns (total 2 columns):
game_id         15489 non-null int64
shots_missed    15489 non-null int64
dtypes: int64(2)
memory usage: 242.1 KB

In [44]:
newnba_df = merge_df(newnba_df,home_miss,on='game_id')
newnba_df[:5].T

,0,1,2,3,4
game_id,21600001,21600001,21600001,21600001,21600001
data_set,2016-2017 Regular Season,2016-2017 Regular Season,2016-2017 Regular Season,2016-2017 Regular Season,2016-2017 Regular Season
date,2016-10-25,2016-10-25,2016-10-25,2016-10-25,2016-10-25
a1,Carmelo Anthony,Carmelo Anthony,Carmelo Anthony,Carmelo Anthony,Carmelo Anthony
a2,Kristaps Porzingis,Kristaps Porzingis,Kristaps Porzingis,Kristaps Porzingis,Kristaps Porzingis
a3,Joakim Noah,Joakim Noah,Joakim Noah,Joakim Noah,Joakim Noah
a4,Courtney Lee,Courtney Lee,Courtney Lee,Courtney Lee,Courtney Lee
a5,Derrick Rose,Derrick Rose,Derrick Rose,Derrick Rose,Derrick Rose
h1,LeBron James,LeBron James,LeBron James,LeBron James,LeBron James
h2,Kevin Love,Kevin Love,Kevin Love,Kevin Love,Kevin Love
h3,Tristan Thompson,Tristan Thompson,Tristan Thompson,Tristan Thompson,Tristan Thompson
h4,JR Smith,JR Smith,JR Smith,JR Smith,JR Smith
h5,Kyrie Irving,Kyrie Irving,Kyrie Irving,Kyrie Irving,Kyrie Irving
period,1,1,1,1,1
away_score,0,0,2,2,2
home_score,0,0,0,0,0
remaining_time,00:12:00,00:12:00,00:11:40,00:11:26,00:11:23
elapsed,00:00:00,00:00:00,00:00:20,00:00:34,00:00:37
play_length,00:00:00,00:00:00,00:00:20,00:00:14,00:00:03
play_id,0,1,2,3,4
team,CLE,NYK,NYK,CLE,NYK
event_type,start of period,jump ball,shot,miss,rebound
assist,NaN,NaN,Joakim Noah,NaN,NaN
away,NaN,Joakim Noah,NaN,NaN,NaN
home,NaN,Tristan Thompson,NaN,NaN,NaN
block,NaN,NaN,NaN,NaN,NaN
entered,NaN,NaN,NaN,NaN,NaN
left,NaN,NaN,NaN,NaN,NaN
num,NaN,NaN,NaN,NaN,NaN
opponent,NaN,NaN,NaN,NaN,NaN
outof,NaN,NaN,NaN,NaN,NaN
player,NaN,Tristan Thompson,Derrick Rose,Kevin Love,Joakim Noah
points,NaN,NaN,2,0,NaN
possession,NaN,Derrick Rose,NaN,NaN,NaN
reason,NaN,NaN,NaN,NaN,NaN
result,NaN,NaN,made,missed,NaN
steal,NaN,NaN,NaN,NaN,NaN
type,start of period,jump ball,Driving Layup,Hook Shot,rebound defensive
shot_distance,NaN,NaN,1,4,NaN
original_x,NaN,NaN,4,-11,NaN
original_y,NaN,NaN,8,36,NaN
converted_x,NaN,NaN,24.6,23.9,NaN
converted_y,NaN,NaN,5.8,85.4,NaN
description,NaN,Jump Ball Thompson vs. Noah: Tip to Rose,Rose 1' Driving Layup (2 PTS) (Noah 1 AST),MISS Love 4' Hook Shot,Noah REBOUND (Off:0 Def:1)
away_team,NYK,NYK,NYK,NYK,NYK
home_team,CLE,CLE,CLE,CLE,CLE
W_or_L,win,win,win,win,win
num_block,72,72,72,72,72
shots_made,45,45,45,45,45
shots_missed,49,49,49,49,49

### Turnover

In [45]:
home_turnover = newnba_df.loc[(newnba_df['team'] == newnba_df['home_team']) & (newnba_df['event_type'] == 'turnover')]\
                                                .groupby('game_id').count()[['event_type']]\
                                                .rename(columns={'event_type':'turnover'})
home_turnover = home_turnover.reset_index()
home_turnover.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15489 entries, 0 to 15488
Data columns (total 2 columns):
game_id     15489 non-null int64
turnover    15489 non-null int64
dtypes: int64(2)
memory usage: 242.1 KB

In [46]:
newnba_df = merge_df(newnba_df,home_turnover,on='game_id')
newnba_df[:5].T

,0,1,2,3,4
game_id,21600001,21600001,21600001,21600001,21600001
data_set,2016-2017 Regular Season,2016-2017 Regular Season,2016-2017 Regular Season,2016-2017 Regular Season,2016-2017 Regular Season
date,2016-10-25,2016-10-25,2016-10-25,2016-10-25,2016-10-25
a1,Carmelo Anthony,Carmelo Anthony,Carmelo Anthony,Carmelo Anthony,Carmelo Anthony
a2,Kristaps Porzingis,Kristaps Porzingis,Kristaps Porzingis,Kristaps Porzingis,Kristaps Porzingis
a3,Joakim Noah,Joakim Noah,Joakim Noah,Joakim Noah,Joakim Noah
a4,Courtney Lee,Courtney Lee,Courtney Lee,Courtney Lee,Courtney Lee
a5,Derrick Rose,Derrick Rose,Derrick Rose,Derrick Rose,Derrick Rose
h1,LeBron James,LeBron James,LeBron James,LeBron James,LeBron James
h2,Kevin Love,Kevin Love,Kevin Love,Kevin Love,Kevin Love
h3,Tristan Thompson,Tristan Thompson,Tristan Thompson,Tristan Thompson,Tristan Thompson
h4,JR Smith,JR Smith,JR Smith,JR Smith,JR Smith
h5,Kyrie Irving,Kyrie Irving,Kyrie Irving,Kyrie Irving,Kyrie Irving
period,1,1,1,1,1
away_score,0,0,2,2,2
home_score,0,0,0,0,0
remaining_time,00:12:00,00:12:00,00:11:40,00:11:26,00:11:23
elapsed,00:00:00,00:00:00,00:00:20,00:00:34,00:00:37
play_length,00:00:00,00:00:00,00:00:20,00:00:14,00:00:03
play_id,0,1,2,3,4
team,CLE,NYK,NYK,CLE,NYK
event_type,start of period,jump ball,shot,miss,rebound
assist,NaN,NaN,Joakim Noah,NaN,NaN
away,NaN,Joakim Noah,NaN,NaN,NaN
home,NaN,Tristan Thompson,NaN,NaN,NaN
block,NaN,NaN,NaN,NaN,NaN
entered,NaN,NaN,NaN,NaN,NaN
left,NaN,NaN,NaN,NaN,NaN
num,NaN,NaN,NaN,NaN,NaN
opponent,NaN,NaN,NaN,NaN,NaN
outof,NaN,NaN,NaN,NaN,NaN
player,NaN,Tristan Thompson,Derrick Rose,Kevin Love,Joakim Noah
points,NaN,NaN,2,0,NaN
possession,NaN,Derrick Rose,NaN,NaN,NaN
reason,NaN,NaN,NaN,NaN,NaN
result,NaN,NaN,made,missed,NaN
steal,NaN,NaN,NaN,NaN,NaN
type,start of period,jump ball,Driving Layup,Hook Shot,rebound defensive
shot_distance,NaN,NaN,1,4,NaN
original_x,NaN,NaN,4,-11,NaN
original_y,NaN,NaN,8,36,NaN
converted_x,NaN,NaN,24.6,23.9,NaN
converted_y,NaN,NaN,5.8,85.4,NaN
description,NaN,Jump Ball Thompson vs. Noah: Tip to Rose,Rose 1' Driving Layup (2 PTS) (Noah 1 AST),MISS Love 4' Hook Shot,Noah REBOUND (Off:0 Def:1)
away_team,NYK,NYK,NYK,NYK,NYK
home_team,CLE,CLE,CLE,CLE,CLE
W_or_L,win,win,win,win,win
num_block,72,72,72,72,72
shots_made,45,45,45,45,45
shots_missed,49,49,49,49,49
turnover,15,15,15,15,15

### Highest Score Per Game

In [47]:
df_home_score = newnba_df.loc[newnba_df['team'] == newnba_df['home_team']].groupby(['game_id', 'player'])['points'].agg(sum)\
                .to_frame('player_score')
df_home_score = df_home_score.reset_index()
df_home_score.head()

    game_id           player  player_score
0  20600001  Alonzo Mourning           1.0
1  20600001   Antoine Walker           9.0
2  20600001      Chris Quinn           2.0
3  20600001    Dorell Wright           2.0
4  20600001      Dwyane Wade          25.0

In [48]:
copy_df_home_score = df_home_score.copy()
copy_df_home_score.head()

    game_id           player  player_score
0  20600001  Alonzo Mourning           1.0
1  20600001   Antoine Walker           9.0
2  20600001      Chris Quinn           2.0
3  20600001    Dorell Wright           2.0
4  20600001      Dwyane Wade          25.0

In [49]:
top_score_players = df_home_score.groupby('game_id').max()['player_score'].to_frame('top_player_score')
top_score_players = top_score_players.reset_index()
top_score_players.head()

    game_id  top_player_score
0  20600001              25.0
1  20600002              34.0
2  20600003              32.0
3  20600004              19.0
4  20600005              27.0

In [50]:
newnba_df = merge_df(newnba_df,top_score_players,on='game_id')
newnba_df[:5].T

,0,1,2,3,4
game_id,21600001,21600001,21600001,21600001,21600001
data_set,2016-2017 Regular Season,2016-2017 Regular Season,2016-2017 Regular Season,2016-2017 Regular Season,2016-2017 Regular Season
date,2016-10-25,2016-10-25,2016-10-25,2016-10-25,2016-10-25
a1,Carmelo Anthony,Carmelo Anthony,Carmelo Anthony,Carmelo Anthony,Carmelo Anthony
a2,Kristaps Porzingis,Kristaps Porzingis,Kristaps Porzingis,Kristaps Porzingis,Kristaps Porzingis
a3,Joakim Noah,Joakim Noah,Joakim Noah,Joakim Noah,Joakim Noah
a4,Courtney Lee,Courtney Lee,Courtney Lee,Courtney Lee,Courtney Lee
a5,Derrick Rose,Derrick Rose,Derrick Rose,Derrick Rose,Derrick Rose
h1,LeBron James,LeBron James,LeBron James,LeBron James,LeBron James
h2,Kevin Love,Kevin Love,Kevin Love,Kevin Love,Kevin Love
h3,Tristan Thompson,Tristan Thompson,Tristan Thompson,Tristan Thompson,Tristan Thompson
h4,JR Smith,JR Smith,JR Smith,JR Smith,JR Smith
h5,Kyrie Irving,Kyrie Irving,Kyrie Irving,Kyrie Irving,Kyrie Irving
period,1,1,1,1,1
away_score,0,0,2,2,2
home_score,0,0,0,0,0
remaining_time,00:12:00,00:12:00,00:11:40,00:11:26,00:11:23
elapsed,00:00:00,00:00:00,00:00:20,00:00:34,00:00:37
play_length,00:00:00,00:00:00,00:00:20,00:00:14,00:00:03
play_id,0,1,2,3,4
team,CLE,NYK,NYK,CLE,NYK
event_type,start of period,jump ball,shot,miss,rebound
assist,NaN,NaN,Joakim Noah,NaN,NaN
away,NaN,Joakim Noah,NaN,NaN,NaN
home,NaN,Tristan Thompson,NaN,NaN,NaN
block,NaN,NaN,NaN,NaN,NaN
entered,NaN,NaN,NaN,NaN,NaN
left,NaN,NaN,NaN,NaN,NaN
num,NaN,NaN,NaN,NaN,NaN
opponent,NaN,NaN,NaN,NaN,NaN
outof,NaN,NaN,NaN,NaN,NaN
player,NaN,Tristan Thompson,Derrick Rose,Kevin Love,Joakim Noah
points,NaN,NaN,2,0,NaN
possession,NaN,Derrick Rose,NaN,NaN,NaN
reason,NaN,NaN,NaN,NaN,NaN
result,NaN,NaN,made,missed,NaN
steal,NaN,NaN,NaN,NaN,NaN
type,start of period,jump ball,Driving Layup,Hook Shot,rebound defensive
shot_distance,NaN,NaN,1,4,NaN
original_x,NaN,NaN,4,-11,NaN
original_y,NaN,NaN,8,36,NaN
converted_x,NaN,NaN,24.6,23.9,NaN
converted_y,NaN,NaN,5.8,85.4,NaN
description,NaN,Jump Ball Thompson vs. Noah: Tip to Rose,Rose 1' Driving Layup (2 PTS) (Noah 1 AST),MISS Love 4' Hook Shot,Noah REBOUND (Off:0 Def:1)
away_team,NYK,NYK,NYK,NYK,NYK
home_team,CLE,CLE,CLE,CLE,CLE
W_or_L,win,win,win,win,win
num_block,72,72,72,72,72
shots_made,45,45,45,45,45
shots_missed,49,49,49,49,49
turnover,15,15,15,15,15
top_player_score,29,29,29,29,29

### Number of Players Over 10points

In [51]:
playersover10 = copy_df_home_score[copy_df_home_score['player_score'] >= 10].groupby('game_id').count()\
                .rename(columns={'player_score':'num_players'})
playersover10 = playersover10.reset_index()
playersover10.drop('player',axis=1,inplace=True)
playersover10.head()

    game_id  num_players
0  20600001            1
1  20600002            4
2  20600003            3
3  20600004            5
4  20600005            4

In [52]:
newnba_df = merge_df(newnba_df,playersover10,on='game_id')
newnba_df[:5].T

,0,1,2,3,4
game_id,21600001,21600001,21600001,21600001,21600001
data_set,2016-2017 Regular Season,2016-2017 Regular Season,2016-2017 Regular Season,2016-2017 Regular Season,2016-2017 Regular Season
date,2016-10-25,2016-10-25,2016-10-25,2016-10-25,2016-10-25
a1,Carmelo Anthony,Carmelo Anthony,Carmelo Anthony,Carmelo Anthony,Carmelo Anthony
a2,Kristaps Porzingis,Kristaps Porzingis,Kristaps Porzingis,Kristaps Porzingis,Kristaps Porzingis
a3,Joakim Noah,Joakim Noah,Joakim Noah,Joakim Noah,Joakim Noah
a4,Courtney Lee,Courtney Lee,Courtney Lee,Courtney Lee,Courtney Lee
a5,Derrick Rose,Derrick Rose,Derrick Rose,Derrick Rose,Derrick Rose
h1,LeBron James,LeBron James,LeBron James,LeBron James,LeBron James
h2,Kevin Love,Kevin Love,Kevin Love,Kevin Love,Kevin Love
h3,Tristan Thompson,Tristan Thompson,Tristan Thompson,Tristan Thompson,Tristan Thompson
h4,JR Smith,JR Smith,JR Smith,JR Smith,JR Smith
h5,Kyrie Irving,Kyrie Irving,Kyrie Irving,Kyrie Irving,Kyrie Irving
period,1,1,1,1,1
away_score,0,0,2,2,2
home_score,0,0,0,0,0
remaining_time,00:12:00,00:12:00,00:11:40,00:11:26,00:11:23
elapsed,00:00:00,00:00:00,00:00:20,00:00:34,00:00:37
play_length,00:00:00,00:00:00,00:00:20,00:00:14,00:00:03
play_id,0,1,2,3,4
team,CLE,NYK,NYK,CLE,NYK
event_type,start of period,jump ball,shot,miss,rebound
assist,NaN,NaN,Joakim Noah,NaN,NaN
away,NaN,Joakim Noah,NaN,NaN,NaN
home,NaN,Tristan Thompson,NaN,NaN,NaN
block,NaN,NaN,NaN,NaN,NaN
entered,NaN,NaN,NaN,NaN,NaN
left,NaN,NaN,NaN,NaN,NaN
num,NaN,NaN,NaN,NaN,NaN
opponent,NaN,NaN,NaN,NaN,NaN
outof,NaN,NaN,NaN,NaN,NaN
player,NaN,Tristan Thompson,Derrick Rose,Kevin Love,Joakim Noah
points,NaN,NaN,2,0,NaN
possession,NaN,Derrick Rose,NaN,NaN,NaN
reason,NaN,NaN,NaN,NaN,NaN
result,NaN,NaN,made,missed,NaN
steal,NaN,NaN,NaN,NaN,NaN
type,start of period,jump ball,Driving Layup,Hook Shot,rebound defensive
shot_distance,NaN,NaN,1,4,NaN
original_x,NaN,NaN,4,-11,NaN
original_y,NaN,NaN,8,36,NaN
converted_x,NaN,NaN,24.6,23.9,NaN
converted_y,NaN,NaN,5.8,85.4,NaN
description,NaN,Jump Ball Thompson vs. Noah: Tip to Rose,Rose 1' Driving Layup (2 PTS) (Noah 1 AST),MISS Love 4' Hook Shot,Noah REBOUND (Off:0 Def:1)
away_team,NYK,NYK,NYK,NYK,NYK
home_team,CLE,CLE,CLE,CLE,CLE
W_or_L,win,win,win,win,win
num_block,72,72,72,72,72
shots_made,45,45,45,45,45
shots_missed,49,49,49,49,49
turnover,15,15,15,15,15
top_player_score,29,29,29,29,29
num_players,4,4,4,4,4

### Assist

In [53]:
home_assist = newnba_df.loc[newnba_df['team'] == newnba_df['home_team']].groupby('game_id').count()[['assist']]\
              .rename(columns={'assist':'num_assist'})
home_assist = home_assist.reset_index()
home_assist.head()

    game_id  num_assist
0  20600001          13
1  20600002          30
2  20600003          19
3  20600004          23
4  20600005          21

In [54]:
newnba_df = merge_df(newnba_df,home_assist,on='game_id')
newnba_df[:5].T

,0,1,2,3,4
game_id,21600001,21600001,21600001,21600001,21600001
data_set,2016-2017 Regular Season,2016-2017 Regular Season,2016-2017 Regular Season,2016-2017 Regular Season,2016-2017 Regular Season
date,2016-10-25,2016-10-25,2016-10-25,2016-10-25,2016-10-25
a1,Carmelo Anthony,Carmelo Anthony,Carmelo Anthony,Carmelo Anthony,Carmelo Anthony
a2,Kristaps Porzingis,Kristaps Porzingis,Kristaps Porzingis,Kristaps Porzingis,Kristaps Porzingis
a3,Joakim Noah,Joakim Noah,Joakim Noah,Joakim Noah,Joakim Noah
a4,Courtney Lee,Courtney Lee,Courtney Lee,Courtney Lee,Courtney Lee
a5,Derrick Rose,Derrick Rose,Derrick Rose,Derrick Rose,Derrick Rose
h1,LeBron James,LeBron James,LeBron James,LeBron James,LeBron James
h2,Kevin Love,Kevin Love,Kevin Love,Kevin Love,Kevin Love
h3,Tristan Thompson,Tristan Thompson,Tristan Thompson,Tristan Thompson,Tristan Thompson
h4,JR Smith,JR Smith,JR Smith,JR Smith,JR Smith
h5,Kyrie Irving,Kyrie Irving,Kyrie Irving,Kyrie Irving,Kyrie Irving
period,1,1,1,1,1
away_score,0,0,2,2,2
home_score,0,0,0,0,0
remaining_time,00:12:00,00:12:00,00:11:40,00:11:26,00:11:23
elapsed,00:00:00,00:00:00,00:00:20,00:00:34,00:00:37
play_length,00:00:00,00:00:00,00:00:20,00:00:14,00:00:03
play_id,0,1,2,3,4
team,CLE,NYK,NYK,CLE,NYK
event_type,start of period,jump ball,shot,miss,rebound
assist,NaN,NaN,Joakim Noah,NaN,NaN
away,NaN,Joakim Noah,NaN,NaN,NaN
home,NaN,Tristan Thompson,NaN,NaN,NaN
block,NaN,NaN,NaN,NaN,NaN
entered,NaN,NaN,NaN,NaN,NaN
left,NaN,NaN,NaN,NaN,NaN
num,NaN,NaN,NaN,NaN,NaN
opponent,NaN,NaN,NaN,NaN,NaN
outof,NaN,NaN,NaN,NaN,NaN
player,NaN,Tristan Thompson,Derrick Rose,Kevin Love,Joakim Noah
points,NaN,NaN,2,0,NaN
possession,NaN,Derrick Rose,NaN,NaN,NaN
reason,NaN,NaN,NaN,NaN,NaN
result,NaN,NaN,made,missed,NaN
steal,NaN,NaN,NaN,NaN,NaN
type,start of period,jump ball,Driving Layup,Hook Shot,rebound defensive
shot_distance,NaN,NaN,1,4,NaN
original_x,NaN,NaN,4,-11,NaN
original_y,NaN,NaN,8,36,NaN
converted_x,NaN,NaN,24.6,23.9,NaN
converted_y,NaN,NaN,5.8,85.4,NaN
description,NaN,Jump Ball Thompson vs. Noah: Tip to Rose,Rose 1' Driving Layup (2 PTS) (Noah 1 AST),MISS Love 4' Hook Shot,Noah REBOUND (Off:0 Def:1)
away_team,NYK,NYK,NYK,NYK,NYK
home_team,CLE,CLE,CLE,CLE,CLE
W_or_L,win,win,win,win,win
num_block,72,72,72,72,72
shots_made,45,45,45,45,45
shots_missed,49,49,49,49,49
turnover,15,15,15,15,15
top_player_score,29,29,29,29,29
num_players,4,4,4,4,4
num_assist,31,31,31,31,31

### Freethrows

In [55]:
ft = newnba_df.loc[:,['game_id','team','home_team','event_type','result']]
ft.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7002072 entries, 0 to 7002071
Data columns (total 5 columns):
game_id       int64
team          object
home_team     object
event_type    object
result        object
dtypes: int64(1), object(4)
memory usage: 320.5+ MB

In [56]:
ft_total = ft.loc[(ft['team'] == ft['home_team']) & (ft['event_type'] == 'free throw')]\
           .groupby('game_id').count()[['event_type']]
ft_total.head()

          event_type
game_id
20600001          22
20600002          24
20600003          25
20600004          32
20600005          42

In [57]:
ft_by_result = ft.loc[(ft['team'] == ft['home_team']) & (ft['event_type'] == 'free throw') & (ft['result']=='made')]\
               .groupby(['game_id']).size().to_frame('count')
ft_by_result = ft_by_result.reset_index()
ft_by_result.head()

    game_id  count
0  20600001     13
1  20600002     16
2  20600003     23
3  20600004     21
4  20600005     33

In [58]:
ft_home = ft_by_result.join(ft_total,on='game_id',how='outer')
ft_home.rename(columns={'event_type':'ft_total'}, inplace=True)
ft_home.head()

    game_id  count  ft_total
0  20600001     13        22
1  20600002     16        24
2  20600003     23        25
3  20600004     21        32
4  20600005     33        42

In [59]:
ft_home['ft_pct'] = ft_home['count']/ft_home['ft_total']
ft_home.head()

/home/bocalbos/anaconda3/lib/python3.5/site-packages/pandas/core/computation/check.py:19: UserWarning: The installed version of numexpr 2.5 is not supported in pandas and will be not be used
The minimum supported version is 2.6.1

  ver=ver, min_ver=_MIN_NUMEXPR_VERSION), UserWarning)

    game_id  count  ft_total    ft_pct
0  20600001     13        22  0.590909
1  20600002     16        24  0.666667
2  20600003     23        25  0.920000
3  20600004     21        32  0.656250
4  20600005     33        42  0.785714

In [60]:
newnba_df = merge_df(newnba_df,ft_home,on='game_id')
newnba_df[:5].T

,0,1,2,3,4
game_id,21600001,21600001,21600001,21600001,21600001
data_set,2016-2017 Regular Season,2016-2017 Regular Season,2016-2017 Regular Season,2016-2017 Regular Season,2016-2017 Regular Season
date,2016-10-25,2016-10-25,2016-10-25,2016-10-25,2016-10-25
a1,Carmelo Anthony,Carmelo Anthony,Carmelo Anthony,Carmelo Anthony,Carmelo Anthony
a2,Kristaps Porzingis,Kristaps Porzingis,Kristaps Porzingis,Kristaps Porzingis,Kristaps Porzingis
a3,Joakim Noah,Joakim Noah,Joakim Noah,Joakim Noah,Joakim Noah
a4,Courtney Lee,Courtney Lee,Courtney Lee,Courtney Lee,Courtney Lee
a5,Derrick Rose,Derrick Rose,Derrick Rose,Derrick Rose,Derrick Rose
h1,LeBron James,LeBron James,LeBron James,LeBron James,LeBron James
h2,Kevin Love,Kevin Love,Kevin Love,Kevin Love,Kevin Love
h3,Tristan Thompson,Tristan Thompson,Tristan Thompson,Tristan Thompson,Tristan Thompson
h4,JR Smith,JR Smith,JR Smith,JR Smith,JR Smith
h5,Kyrie Irving,Kyrie Irving,Kyrie Irving,Kyrie Irving,Kyrie Irving
period,1,1,1,1,1
away_score,0,0,2,2,2
home_score,0,0,0,0,0
remaining_time,00:12:00,00:12:00,00:11:40,00:11:26,00:11:23
elapsed,00:00:00,00:00:00,00:00:20,00:00:34,00:00:37
play_length,00:00:00,00:00:00,00:00:20,00:00:14,00:00:03
play_id,0,1,2,3,4
team,CLE,NYK,NYK,CLE,NYK
event_type,start of period,jump ball,shot,miss,rebound
assist,NaN,NaN,Joakim Noah,NaN,NaN
away,NaN,Joakim Noah,NaN,NaN,NaN
home,NaN,Tristan Thompson,NaN,NaN,NaN
block,NaN,NaN,NaN,NaN,NaN
entered,NaN,NaN,NaN,NaN,NaN
left,NaN,NaN,NaN,NaN,NaN
num,NaN,NaN,NaN,NaN,NaN
opponent,NaN,NaN,NaN,NaN,NaN
outof,NaN,NaN,NaN,NaN,NaN
player,NaN,Tristan Thompson,Derrick Rose,Kevin Love,Joakim Noah
points,NaN,NaN,2,0,NaN
possession,NaN,Derrick Rose,NaN,NaN,NaN
reason,NaN,NaN,NaN,NaN,NaN
result,NaN,NaN,made,missed,NaN
steal,NaN,NaN,NaN,NaN,NaN
type,start of period,jump ball,Driving Layup,Hook Shot,rebound defensive
shot_distance,NaN,NaN,1,4,NaN
original_x,NaN,NaN,4,-11,NaN
original_y,NaN,NaN,8,36,NaN
converted_x,NaN,NaN,24.6,23.9,NaN
converted_y,NaN,NaN,5.8,85.4,NaN
description,NaN,Jump Ball Thompson vs. Noah: Tip to Rose,Rose 1' Driving Layup (2 PTS) (Noah 1 AST),MISS Love 4' Hook Shot,Noah REBOUND (Off:0 Def:1)
away_team,NYK,NYK,NYK,NYK,NYK
home_team,CLE,CLE,CLE,CLE,CLE
W_or_L,win,win,win,win,win
num_block,72,72,72,72,72
shots_made,45,45,45,45,45
shots_missed,49,49,49,49,49
turnover,15,15,15,15,15
top_player_score,29,29,29,29,29
num_players,4,4,4,4,4
num_assist,31,31,31,31,31
count,14,14,14,14,14
ft_total,19,19,19,19,19
ft_pct,0.736842,0.736842,0.736842,0.736842,0.736842

### Last 2 mins score

In [61]:
import datetime

In [62]:
newnba_df['remaining_time'] = pd.to_datetime(newnba_df['remaining_time'],format='%H:%M:%S').dt.time

In [63]:
df_last_2_min = newnba_df.loc[(newnba_df['period'] > 3) & (newnba_df['remaining_time'] < datetime.time(0, 2, 0))]
df_last_2_min.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 458280 entries, 469 to 7002071
Data columns (total 57 columns):
game_id             458280 non-null int64
data_set            458280 non-null object
date                458280 non-null object
a1                  458280 non-null object
a2                  458280 non-null object
a3                  458280 non-null object
a4                  458280 non-null object
a5                  458280 non-null object
h1                  458280 non-null object
h2                  458280 non-null object
h3                  458280 non-null object
h4                  458280 non-null object
h5                  458280 non-null object
period              458280 non-null int64
away_score          458280 non-null int64
home_score          458280 non-null int64
remaining_time      458280 non-null object
elapsed             458280 non-null object
play_length         458280 non-null object
play_id             458280 non-null int64
team                458280 non-null object
event_type          458280 non-null object
assist              26896 non-null object
away                785 non-null object
home                785 non-null object
block               7464 non-null object
entered             53042 non-null object
left                53042 non-null object
num                 72588 non-null float64
opponent            44769 non-null object
outof               72588 non-null float64
player              386588 non-null object
points              197845 non-null float64
possession          686 non-null object
reason              65299 non-null object
result              197845 non-null object
steal               10878 non-null object
type                458280 non-null object
shot_distance       125257 non-null object
original_x          125257 non-null object
original_y          125257 non-null object
converted_x         125257 non-null object
converted_y         125257 non-null object
description         437404 non-null object
away_team           458280 non-null object
home_team           458280 non-null object
W_or_L              401432 non-null object
num_block           458280 non-null int64
shots_made          458280 non-null int64
shots_missed        458280 non-null int64
turnover            458280 non-null int64
top_player_score    458280 non-null float64
num_players         458255 non-null float64
num_assist          458280 non-null int64
count               458280 non-null int64
ft_total            458280 non-null int64
ft_pct              458280 non-null float64
dtypes: float64(6), int64(12), object(39)
memory usage: 202.8+ MB

In [64]:
free_throw_last_2_min = df_last_2_min.loc[df_last_2_min['event_type'] == 'free throw'].groupby('game_id')\
                        .count()[['event_type']].rename(columns={'event_type':'ft_last2min'})      
free_throw_last_2_min = free_throw_last_2_min.reset_index()
free_throw_last_2_min.head()

    game_id  ft_last2min
0  20600001            2
1  20600002            2
2  20600003            2
3  20600004           12
4  20600005            4

In [65]:
newnba_df = merge_df(newnba_df,free_throw_last_2_min,on='game_id')
newnba_df[:5].T

,0,1,2,3,4
game_id,21600001,21600001,21600001,21600001,21600001
data_set,2016-2017 Regular Season,2016-2017 Regular Season,2016-2017 Regular Season,2016-2017 Regular Season,2016-2017 Regular Season
date,2016-10-25,2016-10-25,2016-10-25,2016-10-25,2016-10-25
a1,Carmelo Anthony,Carmelo Anthony,Carmelo Anthony,Carmelo Anthony,Carmelo Anthony
a2,Kristaps Porzingis,Kristaps Porzingis,Kristaps Porzingis,Kristaps Porzingis,Kristaps Porzingis
a3,Joakim Noah,Joakim Noah,Joakim Noah,Joakim Noah,Joakim Noah
a4,Courtney Lee,Courtney Lee,Courtney Lee,Courtney Lee,Courtney Lee
a5,Derrick Rose,Derrick Rose,Derrick Rose,Derrick Rose,Derrick Rose
h1,LeBron James,LeBron James,LeBron James,LeBron James,LeBron James
h2,Kevin Love,Kevin Love,Kevin Love,Kevin Love,Kevin Love
h3,Tristan Thompson,Tristan Thompson,Tristan Thompson,Tristan Thompson,Tristan Thompson
h4,JR Smith,JR Smith,JR Smith,JR Smith,JR Smith
h5,Kyrie Irving,Kyrie Irving,Kyrie Irving,Kyrie Irving,Kyrie Irving
period,1,1,1,1,1
away_score,0,0,2,2,2
home_score,0,0,0,0,0
remaining_time,00:12:00,00:12:00,00:11:40,00:11:26,00:11:23
elapsed,00:00:00,00:00:00,00:00:20,00:00:34,00:00:37
play_length,00:00:00,00:00:00,00:00:20,00:00:14,00:00:03
play_id,0,1,2,3,4
team,CLE,NYK,NYK,CLE,NYK
event_type,start of period,jump ball,shot,miss,rebound
assist,NaN,NaN,Joakim Noah,NaN,NaN
away,NaN,Joakim Noah,NaN,NaN,NaN
home,NaN,Tristan Thompson,NaN,NaN,NaN
block,NaN,NaN,NaN,NaN,NaN
entered,NaN,NaN,NaN,NaN,NaN
left,NaN,NaN,NaN,NaN,NaN
num,NaN,NaN,NaN,NaN,NaN
opponent,NaN,NaN,NaN,NaN,NaN
outof,NaN,NaN,NaN,NaN,NaN
player,NaN,Tristan Thompson,Derrick Rose,Kevin Love,Joakim Noah
points,NaN,NaN,2,0,NaN
possession,NaN,Derrick Rose,NaN,NaN,NaN
reason,NaN,NaN,NaN,NaN,NaN
result,NaN,NaN,made,missed,NaN
steal,NaN,NaN,NaN,NaN,NaN
type,start of period,jump ball,Driving Layup,Hook Shot,rebound defensive
shot_distance,NaN,NaN,1,4,NaN
original_x,NaN,NaN,4,-11,NaN
original_y,NaN,NaN,8,36,NaN
converted_x,NaN,NaN,24.6,23.9,NaN
converted_y,NaN,NaN,5.8,85.4,NaN
description,NaN,Jump Ball Thompson vs. Noah: Tip to Rose,Rose 1' Driving Layup (2 PTS) (Noah 1 AST),MISS Love 4' Hook Shot,Noah REBOUND (Off:0 Def:1)
away_team,NYK,NYK,NYK,NYK,NYK
home_team,CLE,CLE,CLE,CLE,CLE
W_or_L,win,win,win,win,win
num_block,72,72,72,72,72
shots_made,45,45,45,45,45
shots_missed,49,49,49,49,49
turnover,15,15,15,15,15
top_player_score,29,29,29,29,29
num_players,4,4,4,4,4
num_assist,31,31,31,31,31
count,14,14,14,14,14
ft_total,19,19,19,19,19
ft_pct,0.736842,0.736842,0.736842,0.736842,0.736842
ft_last2min,2,2,2,2,2

### Net score within last 2 mins

In [66]:
net_win_points_last_2mins = pd.DataFrame(df_last_2_min[['game_id', 'away_score', 'home_score', 'remaining_time']]\
                            .groupby('game_id')['home_score'].agg(np.ptp) -\
                            df_last_2_min[['game_id', 'away_score', 'home_score', 'remaining_time']]\
                            .groupby('game_id')['away_score'].agg(np.ptp),columns=['scorediff'])
net_win_points_last_2mins = net_win_points_last_2mins.reset_index()
net_win_points_last_2mins.head()

/home/bocalbos/anaconda3/lib/python3.5/site-packages/numpy/core/fromnumeric.py:2495: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)

    game_id  scorediff
0  20600001         -6
1  20600002         -2
2  20600003          0
3  20600004          4
4  20600005          1

In [67]:
newnba_df = merge_df(newnba_df,net_win_points_last_2mins,on='game_id')
newnba_df[:5].T

,0,1,2,3,4
game_id,21600001,21600001,21600001,21600001,21600001
data_set,2016-2017 Regular Season,2016-2017 Regular Season,2016-2017 Regular Season,2016-2017 Regular Season,2016-2017 Regular Season
date,2016-10-25,2016-10-25,2016-10-25,2016-10-25,2016-10-25
a1,Carmelo Anthony,Carmelo Anthony,Carmelo Anthony,Carmelo Anthony,Carmelo Anthony
a2,Kristaps Porzingis,Kristaps Porzingis,Kristaps Porzingis,Kristaps Porzingis,Kristaps Porzingis
a3,Joakim Noah,Joakim Noah,Joakim Noah,Joakim Noah,Joakim Noah
a4,Courtney Lee,Courtney Lee,Courtney Lee,Courtney Lee,Courtney Lee
a5,Derrick Rose,Derrick Rose,Derrick Rose,Derrick Rose,Derrick Rose
h1,LeBron James,LeBron James,LeBron James,LeBron James,LeBron James
h2,Kevin Love,Kevin Love,Kevin Love,Kevin Love,Kevin Love
h3,Tristan Thompson,Tristan Thompson,Tristan Thompson,Tristan Thompson,Tristan Thompson
h4,JR Smith,JR Smith,JR Smith,JR Smith,JR Smith
h5,Kyrie Irving,Kyrie Irving,Kyrie Irving,Kyrie Irving,Kyrie Irving
period,1,1,1,1,1
away_score,0,0,2,2,2
home_score,0,0,0,0,0
remaining_time,00:12:00,00:12:00,00:11:40,00:11:26,00:11:23
elapsed,00:00:00,00:00:00,00:00:20,00:00:34,00:00:37
play_length,00:00:00,00:00:00,00:00:20,00:00:14,00:00:03
play_id,0,1,2,3,4
team,CLE,NYK,NYK,CLE,NYK
event_type,start of period,jump ball,shot,miss,rebound
assist,NaN,NaN,Joakim Noah,NaN,NaN
away,NaN,Joakim Noah,NaN,NaN,NaN
home,NaN,Tristan Thompson,NaN,NaN,NaN
block,NaN,NaN,NaN,NaN,NaN
entered,NaN,NaN,NaN,NaN,NaN
left,NaN,NaN,NaN,NaN,NaN
num,NaN,NaN,NaN,NaN,NaN
opponent,NaN,NaN,NaN,NaN,NaN
outof,NaN,NaN,NaN,NaN,NaN
player,NaN,Tristan Thompson,Derrick Rose,Kevin Love,Joakim Noah
points,NaN,NaN,2,0,NaN
possession,NaN,Derrick Rose,NaN,NaN,NaN
reason,NaN,NaN,NaN,NaN,NaN
result,NaN,NaN,made,missed,NaN
steal,NaN,NaN,NaN,NaN,NaN
type,start of period,jump ball,Driving Layup,Hook Shot,rebound defensive
shot_distance,NaN,NaN,1,4,NaN
original_x,NaN,NaN,4,-11,NaN
original_y,NaN,NaN,8,36,NaN
converted_x,NaN,NaN,24.6,23.9,NaN
converted_y,NaN,NaN,5.8,85.4,NaN
description,NaN,Jump Ball Thompson vs. Noah: Tip to Rose,Rose 1' Driving Layup (2 PTS) (Noah 1 AST),MISS Love 4' Hook Shot,Noah REBOUND (Off:0 Def:1)
away_team,NYK,NYK,NYK,NYK,NYK
home_team,CLE,CLE,CLE,CLE,CLE
W_or_L,win,win,win,win,win
num_block,72,72,72,72,72
shots_made,45,45,45,45,45
shots_missed,49,49,49,49,49
turnover,15,15,15,15,15
top_player_score,29,29,29,29,29
num_players,4,4,4,4,4
num_assist,31,31,31,31,31
count,14,14,14,14,14
ft_total,19,19,19,19,19
ft_pct,0.736842,0.736842,0.736842,0.736842,0.736842
ft_last2min,2,2,2,2,2
scorediff,0,0,0,0,0

In [68]:
index = newnba_df[newnba_df['play_id'] == 0].index.values - 1
index = np.delete(index, 0)
index = np.append(index, finalnba_df.shape[0] - 1)
index

array([    485,     903,    1380, ..., 6401805, 6402222, 7002071])

In [69]:
working_df=newnba_df[newnba_df.index.isin(index)]
working_df[:1].T

                                       485
game_id                           21600001
data_set          2016-2017 Regular Season
date                            2016-10-25
a1                               Ron Baker
a2                            Kyle O'Quinn
a3                       Willy Hernangomez
a4                    Mindaugas Kuzminskas
a5                           Sasha Vujacic
h1                           Mike Dunleavy
h2                         DeAndre Liggins
h3                          Chris Andersen
h4                            Jordan McRae
h5                             James Jones
period                                   4
away_score                              88
home_score                             117
remaining_time                    00:00:00
elapsed                           00:12:00
play_length                       00:00:12
play_id                                600
team                                   CLE
event_type                   end of period
assist                                 NaN
away                                   NaN
home                                   NaN
block                                  NaN
entered                                NaN
left                                   NaN
num                                    NaN
opponent                               NaN
outof                                  NaN
player                                 NaN
points                                 NaN
possession                             NaN
reason                                 NaN
result                                 NaN
steal                                  NaN
type                         end of period
shot_distance                          NaN
original_x                             NaN
original_y                             NaN
converted_x                            NaN
converted_y                            NaN
description                            NaN
away_team                              NYK
home_team                              CLE
W_or_L                                 win
num_block                               72
shots_made                              45
shots_missed                            49
turnover                                15
top_player_score                        29
num_players                              4
num_assist                              31
count                                   14
ft_total                                19
ft_pct                            0.736842
ft_last2min                              2
scorediff                                0

In [70]:
working_df = working_df.loc[:,['game_id','data_set','date','away_score','home_score','away_team','home_team',\
                                         'W_or_L','num_block','shots_made','shots_missed','turnover','top_player_score',\
                                         'num_players','num_assist','ft_last2min','ft_total','ft_pct',\
                                         'scorediff']]
working_df[:1].T

                                       485
game_id                           21600001
data_set          2016-2017 Regular Season
date                            2016-10-25
away_score                              88
home_score                             117
away_team                              NYK
home_team                              CLE
W_or_L                                 win
num_block                               72
shots_made                              45
shots_missed                            49
turnover                                15
top_player_score                        29
num_players                              4
num_assist                              31
ft_last2min                              2
ft_total                                19
ft_pct                            0.736842
scorediff                                0

In [71]:
working_df['fg_pct'] = working_df['shots_made']/(working_df['shots_made']+working_df['shots_missed'])
working_df[:1].T

                                       485
game_id                           21600001
data_set          2016-2017 Regular Season
date                            2016-10-25
away_score                              88
home_score                             117
away_team                              NYK
home_team                              CLE
W_or_L                                 win
num_block                               72
shots_made                              45
shots_missed                            49
turnover                                15
top_player_score                        29
num_players                              4
num_assist                              31
ft_last2min                              2
ft_total                                19
ft_pct                            0.736842
scorediff                                0
fg_pct                            0.478723

In [72]:
working_df.to_csv('working_nba_df.csv')

## Additional Reference

https://www.slideshare.net/ThomasSalierno/national-basketball-association-industry-analysis